<?php
$data = array (
  0 => 
  array (
    'goods_id' => '892',
    'cat_id' => '898',
    'goods_name' => '宝莲 透净瞬洁净妆乳 120ml 卸妆乳 卸妆液卸妆无残留专柜正品 安全温和 彻底清洁 水润清爽',
    'market_price' => '<em>¥</em>82.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '69.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>69.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224493829.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224493156.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '宝莲 透净瞬洁净妆乳 120ml 卸妆乳 卸妆液卸妆无残留专柜正品 安全温和 彻底清洁 水润清爽',
    'url' => 'goods.php?id=892',
  ),
  1 => 
  array (
    'goods_id' => '891',
    'cat_id' => '898',
    'goods_name' => '美宝莲 好气色潮色双搭轻垫霜提亮肌肤白皙气垫CC霜凸显好气色 提亮肌肤',
    'market_price' => '<em>¥</em>226.79',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '189.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>189.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224462655.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224462030.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲 好气色潮色双搭轻垫霜提亮肌肤白皙气垫CC霜凸显好气色 提亮肌肤',
    'url' => 'goods.php?id=891',
  ),
  2 => 
  array (
    'goods_id' => '890',
    'cat_id' => '898',
    'goods_name' => '美宝莲 顺滑恒久眉笔流畅线条 利落型眉 可长久持妆 新品上市 流畅线条 利落型眉 长效持妆',
    'market_price' => '<em>¥</em>58.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '49.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>49.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224435682.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224435572.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲 顺滑恒久眉笔流畅线条 利落型眉 可长久持妆 新品上市 流畅线条 利落型眉 长效持妆',
    'url' => 'goods.php?id=890',
  ),
  3 => 
  array (
    'goods_id' => '889',
    'cat_id' => '898',
    'goods_name' => '美宝莲 奇妙净颜盈润洁面膏100ml 保湿 控油 滋润 祛除多余油脂 不干燥 不紧绷',
    'market_price' => '<em>¥</em>58.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '49.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>49.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224406928.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224406873.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲 奇妙净颜盈润洁面膏100ml 保湿 控油 滋润 祛除多余油脂 不干燥 不紧绷',
    'url' => 'goods.php?id=889',
  ),
  4 => 
  array (
    'goods_id' => '888',
    'cat_id' => '898',
    'goods_name' => '美宝莲 精纯矿物专业彩妆化妆刷 散粉刷 腮红刷 粉底刷 山羊毛 专业彩妆化妆刷',
    'market_price' => '<em>¥</em>23.88',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '19.90',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>19.90',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224379045.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224379217.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲 精纯矿物专业彩妆化妆刷 散粉刷 腮红刷 粉底刷 山羊毛 专业彩妆化妆刷',
    'url' => 'goods.php?id=888',
  ),
  5 => 
  array (
    'goods_id' => '887',
    'cat_id' => '898',
    'goods_name' => '美宝莲 色秀指甲油 糖果色 专业彩妆美甲 专柜正品 绚丽色彩 多色可选',
    'market_price' => '<em>¥</em>34.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '29.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>29.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224351677.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224351590.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲 色秀指甲油 糖果色 专业彩妆美甲 专柜正品 绚丽色彩 多色可选',
    'url' => 'goods.php?id=887',
  ),
  6 => 
  array (
    'goods_id' => '886',
    'cat_id' => '898',
    'goods_name' => 'Maybelline/美宝莲净澈多效卸妆水清爽型 舒缓 深层清洁 舒缓 补水 深层清洁 卸妆',
    'market_price' => '<em>¥</em>118.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '99.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>99.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224320245.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224320138.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => 'Maybelline/美宝莲净澈多效卸妆水清爽型 舒缓 深层清洁 舒缓 补水 深层清洁 卸妆',
    'url' => 'goods.php?id=886',
  ),
  7 => 
  array (
    'goods_id' => '885',
    'cat_id' => '898',
    'goods_name' => '美宝莲宝蓓护唇膏 宝贝护唇膏 润唇膏 唇彩口红保湿 滋润',
    'market_price' => '<em>¥</em>28.79',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '24.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>24.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224291051.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224291042.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲宝蓓护唇膏 宝贝护唇膏 润唇膏 唇彩口红保湿 滋润',
    'url' => 'goods.php?id=885',
  ),
  8 => 
  array (
    'goods_id' => '884',
    'cat_id' => '898',
    'goods_name' => '美宝莲 宝蓓爱炫彩护唇膏 润唇膏 波普风 保湿滋润 显色丰润 一扫唇色暗沉 卖萌必备',
    'market_price' => '<em>¥</em>34.80',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '29.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>29.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1490224263857.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1490224263978.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '美宝莲 宝蓓爱炫彩护唇膏 润唇膏 波普风 保湿滋润 显色丰润 一扫唇色暗沉 卖萌必备',
    'url' => 'goods.php?id=884',
  ),
  9 => 
  array (
    'goods_id' => '645',
    'cat_id' => '884',
    'goods_name' => '杰威尔发胶定型喷雾男士干胶头发持久定型造型啫喱水发蜡蓬松清香 快速定型，蓬松清香，不起白屑，买2送1',
    'market_price' => '<em>¥</em>132.00',
    'model_attr' => '0',
    'goods_sort' => NULL,
    'sort_order' => '100',
    'org_price' => '110.00',
    'promote_price' => '',
    'shop_price' => '<em>¥</em>110.00',
    'is_promote' => '0',
    'promote_start_date' => '0',
    'promote_end_date' => '0',
    'goods_brief' => '',
    'goods_thumb' => 'images/201703/thumb_img/0_thumb_G_1489105083498.jpg',
    'goods_img' => 'images/201703/goods_img/0_G_1489105083317.jpg',
    'product_price' => '0.00',
    'product_promote_price' => '0.00',
    'short_name' => '杰威尔发胶定型喷雾男士干胶头发持久定型造型啫喱水发蜡蓬松清香 快速定型，蓬松清香，不起白屑，买2送1',
    'url' => 'goods.php?id=645',
  ),
);
?>